spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    password: root
    user: root
server:
  port: 8093